src/MvcBurger.Presentation/MvcBurger.Web/Controllers/AccessController.cs
using MediatR;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Options;
using MvcBurger.Application.Exceptions.BadRequestException;
using MvcBurger.Application.Features.Users.Commands.Create;
using MvcBurger.Application.Features.Users.Queries.Login;
using MvcBurger.Application.Features.Users.Queries.Logout;
using MvcBurger.Domain.Entities;
using MvcBurger.Web.Models.VMs;

namespace MvcBurger.Web.Controllers
{
    public class AccessController : Controller
    {
        private readonly IMediator _mediator;

        public AccessController(IMediator mediator)
        {
            _mediator = mediator;
        }
        [Route("u/Login")]
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        [Route("u/Login")]
        public async Task<IActionResult> Login(UserLoginVM loginVM, string? returnUrl)
        {

            if (ModelState.IsValid)
            {

                LoginAppUserRequest request = new LoginAppUserRequest()
                {
                    Password = loginVM.Password,
                    Email = loginVM.Email
                };
                LoginAppUserResponse loginResponse;

                loginResponse = await _mediator.Send(request);

                if (loginResponse.UserId is null)
                    return View();

                HttpContext.Session.SetString("userId", loginResponse.UserId);
                HttpContext.Session.SetString("roles", string.Join(",", loginResponse.Roles));

                if (loginResponse.Roles.Contains("Admin"))
                    return RedirectToAction("Menus", "Home", new { area = "Admin" });

                if (returnUrl is null)
                    return RedirectToAction("Index", "Home");

                return Redirect(returnUrl);
            }

            return View(loginVM);
        }
        [Route("u/Register")]
        public IActionResult Register()
        {
            return View();
        }
        [Route("u/Register")]
        [HttpPost]
        public async Task<IActionResult> Register(CreateUserVM userVM)
        {
            if (ModelState.IsValid)
            {
                var request = new CreateAppUserRequest()
                {
                    Address = userVM.Address,
                    Password = userVM.Password,
                    Email = userVM.Email,
                    Firstname = userVM.Firstname,
                    Lastname = userVM.Lastname
                };
                CreateAppUserResponse response;
                try
                {
                    response = await _mediator.Send(request);
                }
                catch (Exception)
                {
                    return View();
                }
                if (response.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewBag.errorMessage = userVM.Email + " is already in use!";
                    return View(userVM);
                }
            }
            return View(userVM);
        }
        public async Task<IActionResult> Logout()
        {
            LogoutAppUserRequest request = new LogoutAppUserRequest();
            await _mediator.Send(request);
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }
    }
}

src/MvcBurger.Presentation/MvcBurger.Web/Controllers/OrderController.cs
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MvcBurger.Application.Features.ExtraIngredients.Queries.GetAll;
using MvcBurger.Application.Features.Menus.Queries.GetById;
using MvcBurger.Application.Features.OrderItems.Queries.GetById;
using MvcBurger.Application.Features.Orders.Commands.Cart.AddToCart;
using MvcBurger.Application.Features.Orders.Commands.Cart.Checkout;
using MvcBurger.Application.Features.Orders.Commands.Cart.Common;
using MvcBurger.Application.Features.Orders.Commands.Cart.DeleteCartItem;
using MvcBurger.Application.Features.Orders.Commands.Cart.UpdateCartItem;
using MvcBurger.Application.Features.Orders.Queries.GetCartByUserId;
using MvcBurger.Application.Features.Queries.Drinks.GetAll;
using MvcBurger.Web.Models.VMs;

namespace MvcBurger.Web.Controllers
{
    //_Otder layout ile, OrderPartial layout birlesecek
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IMediator _mediator;

        public OrderController(IMediator mediator)
        {
            _mediator = mediator;
        }

        [Route("od/menu-{id}")]
        [HttpGet]
        public async Task<IActionResult> CreateOrder(Guid Id) // Order Creation Page
        {
            TempData["submitAction"] = nameof(CreateOrder);
            var menuResponse = await _mediator.Send(new GetByIdMenuRequest() { Id = Id });

            var fields = (await GetFields());

            SelectedMenuVM selected = new SelectedMenuVM()
            {
                MenuId = menuResponse.Id,
                Description = menuResponse.Description,
                ImageUrl = menuResponse.ImageUrl,
                Name = menuResponse.Name,
                Price = menuResponse.Price
            };

            selected.AllExtraIngredients = fields.ingredients.List.ToList();
            selected.AllDrinks = fields.drinks.List.ToList();

            selected.Extras = selected.AllExtraIngredients.Select(ei => new SelectedExtraItem
            {
                ExtraName = ei.Name,
                SelectedIngredientId = ei.Id,
            }).ToList();

            string js = System.Text.Json.JsonSerializer.Serialize(selected);

            TempData["selectedMenu"] = js;

            return PartialView("CreateUpdateOrder", selected);
        }

        [Route("od/menu-{id}")]
        [HttpPost]
        public async Task<IActionResult> CreateOrder(SelectedMenuVM selected)
        {
            var selectedTemp = System.Text.Json.JsonSerializer.Deserialize<SelectedMenuVM>(TempData["selectedMenu"] as string);

            var selectedExtras = selected.Extras.Where(e => e.Checked).Select(e => e.SelectedIngredientId);

            OrderItemRequest orderItemRequest = new OrderItemRequest()
            {
                Size = selected.SelectedSize,
                Amount = selected.Amount,
                DrinkId = selected.SelectedDrinkId,
                MenuId = selectedTemp.MenuId,
                ExtraIngredientId = selectedExtras
            };

            IEnumerable<OrderItemRequest> orderItems = new List<OrderItemRequest>() { orderItemRequest }.AsEnumerable();

            AddToCartRequest addToCartRequest = new AddToCartRequest()
            {
                AppUserId = HttpContext.User.Claims.First().Value,
                OrderItemRequest = orderItems
            };

            var response = await _mediator.Send(addToCartRequest);

            GetUserCartVM userCartVM = new GetUserCartVM() { Cart = response.Cart };

            return RedirectToAction(nameof(Cart), userCartVM);
        }
        [Route("c/")]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public async Task<IActionResult> Cart(GetUserCartVM userCartVM)
        {
            GetCartByUserIdRequest request = new GetCartByUserIdRequest() { AppUserId = HttpContext.User.Claims.First().Value };

                userCartVM.Cart = (await _mediator.Send(request)).Cart;
                return View(userCartVM);
        }
        [Route("co/")]
        public async Task<IActionResult> Checkout()
        {
            await _mediator.Send(new CheckoutRequest() { AppUserId = HttpContext.User.Claims.First().Value });

            return View(nameof(Cart));
        }

        public async Task<IActionResult> RemoveCartItem(Guid Id)
        {
            await _mediator.Send(new DeleteCartItemRequest { AppUserId = HttpContext.User.Claims.First().Value, OrderItemId = Id });
            return RedirectToAction(nameof(Cart));
        }
        [Route("c/order-{id}")]
        public async Task<IActionResult> UpdateCartItem(Guid Id)
        {
            TempData["submitAction"] = nameof(UpdateCartItem);
            var fields = await GetFields();

            GetByIdOrderItemRequest orderItem = new GetByIdOrderItemRequest() { Id = Id };

            var response = await _mediator.Send(orderItem);
            var menuResponse = await _mediator.Send(new GetByIdMenuRequest() { Id = response.MenuId });

            SelectedMenuVM updateMenuVm = new SelectedMenuVM()
            {
                Description = menuResponse.Description,
                ImageUrl = menuResponse.ImageUrl,
                Name = menuResponse.Name,
                Price = menuResponse.Price,
                Amount = response.Amount,
                SelectedDrinkId = response.DrinkId,
                SelectedExtraIngredients = response.OrderItemExtraIngredient,
                MenuId = response.MenuId,
                SelectedSize = response.Size,
                AllDrinks = fields.drinks.List.ToList(),
                AllExtraIngredients = fields.ingredients.List.ToList()

            };

            updateMenuVm.Extras = updateMenuVm.AllExtraIngredients.Select(ei => new SelectedExtraItem
            {
                ExtraName = ei.Name,
                SelectedIngredientId = ei.Id
            }).ToList();

            updateMenuVm.Extras.ForEach(ei =>
            {
                if (updateMenuVm.SelectedExtraIngredients.Any(se => se.ExtraIngredientId == ei.SelectedIngredientId))
                    ei.Checked = true;
            });

            TempData["menuId"] = updateMenuVm.MenuId;

            return PartialView("CreateUpdateOrder", updateMenuVm);
        }

        [Route("c/order-{id}")]
        [HttpPost]
        public async Task<IActionResult> UpdateCartItem(Guid Id, SelectedMenuVM updateMenuVm)
        {


            var menuId = (Guid)TempData["menuId"];


            OrderItemRequest orderitem = new OrderItemRequest
            {
                Amount = updateMenuVm.Amount,
                DrinkId = updateMenuVm.SelectedDrinkId,
                ExtraIngredientId = updateMenuVm.Extras.Where(e => e.Checked).Select(e => e.SelectedIngredientId).ToList(),
                MenuId = menuId,
                Size = updateMenuVm.SelectedSize
            };


            UpdateCartItemRequest request = new UpdateCartItemRequest() { OrderItemId = Id, AppUserId = HttpContext.User.Claims.First().Value, OrderItemRequest = orderitem };

            await _mediator.Send(request);
            return RedirectToAction(nameof(Cart));
        }


        private async Task<(GetAllExtraIngredientsResponse ingredients, GetAllDrinksResponse drinks)>
            GetFields()
        {
            var ingredientsResponse = await _mediator.Send(new GetAllExtraIngredientsRequest());

            var drinksResponse = await _mediator.Send(new GetAllDrinksRequest());

            return (ingredientsResponse, drinksResponse);
        }

    }
}

src/MvcBurger.Presentation/MvcBurger.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MVC Burger</title>

    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css">

    <!-- custom css file link  -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/log.css">

</head>
<body>
    <!-- header section starts  -->

    <header class="header d-flex align-items-stretch justify-content-between pb-2">

        <div id="menu-btn" class="fas fa-bars icons"></div>
        <div></div>
        <nav class="navbar">
            <div class="row justify-content-sm-between">
                <div class="col-sm-2 mt-3">
                    
                        <a class="text-decoration-none" href="#home">home</a>
                    
                </div>
                <div class="col-sm-2 mt-3">
                    
                        <a class="text-decoration-none" href="#menu">menu</a>
                    
                </div>
                <div class="col-sm-4">
                    
                        <!-- Uncomment the line below if you want to wrap the image as well -->
                        <!-- <a href="#home" class="logo"><img src="/images/logo.png" alt=""></a> -->
                        <img src="/images/logo.png" alt="">
                    
                </div>
                <div class="col-sm-2 mt-3">
                    
                        <a class="text-decoration-none" href="#about">about</a>
                    
                </div>
                <div class="col-sm-2 mt-3">
                    
                        <a class="text-decoration-none" href="#contact">contact</a>
                    
                </div>
            </div>
        </nav>
        <div>
            <a asp-action="Cart" asp-controller="Order" class="fas fa-shopping-cart icons me-5"></a>
            @if (!User.Identity.IsAuthenticated)
            {
                <a asp-action="Login" asp-controller="Access" class="fas fa-login icons">Login</a>
                <a asp-action="Register" asp-controller="Access" class="fas fa-register icons">Register</a>
            }
            else
            {
                <a asp-action="Logout" asp-controller="Access" class="fas fa-register icons">Logout</a>
            }
        </div>


    </header>

    <!-- header section ends  -->
    <!-- home section starts  -->

    <section class="home" id="home">

        <div class="content">
            <img data-aos="fade-up" data-aos-delay="150" src="/images/burger-baner.png" alt="">
            <h3 data-aos="fade-up" data-aos-delay="300">So meaty you'll go crazy</h3>
            <p data-aos="fade-up" data-aos-delay="450">MVC Burger</p>
            <a data-aos="fade-up" data-aos-delay="600" href="#menu" class="btn">our menu</a>
        </div>

    </section>

    <!-- home section ends -->
    <!-- service sectioin starts  -->

    <section class="service">

        <div class="box" data-aos="fade-up" data-aos-delay="150">
            <i class="fas fa-hamburger"></i>
            <h3>best quality</h3>
        </div>

        <div class="box" data-aos="fade-up" data-aos-delay="300">
            <i class="fas fa-shipping-fast"></i>
            <h3>free delivery</h3>
        </div>

        <div class="box" data-aos="fade-up" data-aos-delay="450">
            <i class="fas fa-headset"></i>
            <h3>24/7 support</h3>
        </div>


    </section>

    <!-- service sectioin ends -->
    <!-- menu section starts  -->
    @RenderBody()

    <!-- menu section ends -->
    <!-- about section starts  -->

    <section class="about" id="about">

        <div class="image" data-aos="fade-right" data-aos-delay="150">
            <img src="/images/about-img.png" alt="">
        </div>

        <div class="content" data-aos="fade-left" data-aos-delay="300">
            <h3 class="title">Step Into Burger Heaven</h3>
            <p>Delicious burgers</p>
            <div class="icons">
                <h3> <i class="fas fa-check"></i> Best price </h3>
                <h3> <i class="fas fa-check"></i> Best Service </h3>
                <h3> <i class="fas fa-check"></i> Fresh Ingredient </h3>
                <h3> <i class="fas fa-check"></i> Backed Buns </h3>
            </div>
        </div>

    </section>

    <!-- about section ends -->
    <!-- contact section starts  -->

    <section class="contact" id="contact">

        <div class="heading">
            <img src="/images/title-img.png" alt="">
            <h3>Contact Us</h3>
        </div>

        <div class="row">
            <iframe data-aos ="fade-up" data-aos-delay="150" class="map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d48192.27329227498!2d28.98520028552845!3d40.98110681349835!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cac790b17ba89d%3A0xd2d24ea0437a7ee2!2zS2FkxLFrw7Z5L8Swc3RhbmJ1bA!5e0!3m2!1str!2str!4v1700319748062!5m2!1str!2str" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            <div class="form">

                <div class="icons-container">

                    <div class="icons" data-aos="fade-up" data-aos-delay="150">
                        <i class="fas fa-map"></i>
                        <h3>Address :</h3>
                        <p>Istanbul, Turkey - 12345</p>
                    </div>

                    <div class="icons" data-aos="fade-up" data-aos-delay="300">
                        <i class="fas fa-envelope"></i>
                        <h3>Email :</h3>
                        <p>mvcburger@gmail.com</p>
                    </div>

                    <div class="icons" data-aos="fade-up" data-aos-delay="450">
                        <i class="fas fa-phone"></i>
                        <h3>Phone :</h3>
                        <p>+123-456-7890</p>
                        <p>+111-222-3333</p>
                    </div>

                </div>

                <form action="">
                    <input data-aos="fade-up" data-aos-delay="150" type="text" placeholder="full name" class="box">
                    <input data-aos="fade-up" data-aos-delay="300" type="email" placeholder="email" class="box">
                    <input data-aos="fade-up" data-aos-delay="450" type="number" placeholder="phone" class="box">
                    <textarea data-aos="fade-up" data-aos-delay="600" name="" placeholder="message" class="box" id="" cols="30" rows="10"></textarea>
                    <input data-aos="fade-up" data-aos-delay="750" type="submit" value="Send Message" class="btn">
                </form>

            </div>
        </div>
    </section>

    <!-- contact section ends -->
    <!-- footer section starts  -->

    <section class="footer">

        <div class="links">
            <a href="#home" class="btn">home</a>
            <a href="#menu" class="btn">menu</a>
            <a href="#about" class="btn">about</a>
            <a href="#contact" class="btn">contact</a>
        </div>

        <p class="credit"> created by <span><a href="https://freewebsitecode.com/">Free Website Code</a></span> | all rights reserved! </p><br>

    </section>

    <!-- footer section ends -->
    <!-- custom js file link      -->
    <script src="js/script.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>

    <script>

        AOS.init({
            duration: 800,
        });

    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/MvcBurger.Presentation/MvcBurger.Web/Views/Shared/_LoginRegister.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MvcBurger</title>

    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css">

    <!-- custom css file link  -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet" href="/css/log.css">
    

</head>
<body>
    <!-- header section starts  -->

    <header class="header d-flex align-items-stretch justify-content-between pb-2">

        <div id="menu-btn" class="fas fa-bars icons"></div>
        <div></div>
        <nav class="navbar">
            <div class="row justify-content-sm-between">
                <div class="col-sm-2 mt-3">

                    <a class="text-decoration-none" asp-action="Index" asp-controller="Home">home</a>

                </div>
                <div class="col-sm-2 mt-3">

                    <a class="text-decoration-none" asp-action="Index" asp-controller="Home">menu</a>

                </div>
                <div class="col-sm-4">

                    <!-- Uncomment the line below if you want to wrap the image as well -->
                    <!-- <a href="#home" class="logo"><img src="/images/logo.png" alt=""></a> -->
                    <img src="/images/logo.png" alt="">

                </div>
                <div class="col-sm-2 mt-3">

                    <a class="text-decoration-none" asp-action="Index" asp-controller="Home">about</a>

                </div>
                <div class="col-sm-2 mt-3">

                    <a class="text-decoration-none" asp-action="Index" asp-controller="Home">contact</a>

                </div>
            </div>
        </nav>
        <div>
            <a asp-action="Cart" asp-controller="Order" class="fas fa-shopping-cart icons me-5"></a>
            @if (!User.Identity.IsAuthenticated)
            {
                <a asp-action="Login" asp-controller="Access" class="fas fa-login icons">Login</a>
                <a asp-action="Register" asp-controller="Access" class="fas fa-register icons">Register</a>
            }
            else
            {
                <a asp-action="Logout" asp-controller="Access" class="fas fa-register icons">Logout</a>
            }
        </div>
    </header>

    <!-- header section ends  -->
    <!-- home section starts  -->

    <section class="home" id="home">

        <div class="content">
            @RenderBody()

            
        </div>

    </section>

    <!-- home section ends -->
    
    <!-- contact section starts  -->

    <section class="contact" id="contact">
                

    </section>

    <!-- contact section ends -->
    <!-- footer section starts  -->

    <section class="footer">

        <div class="links">
            <a asp-action="Index" asp-controller="Home" class="btn">home</a>
            <a asp-action="Index" asp-controller="Home" class="btn">menu</a>
            <a asp-action="Index" asp-controller="Home" class="btn">about</a>
            <a asp-action="Index" asp-controller="Home" class="btn">contact</a>
        </div>

        <p class="credit"> created by <span><a href="https://freewebsitecode.com/">Free Website Code</a></span> | all rights reserved! </p><br>

    </section>

    <!-- footer section ends -->
    <!-- custom js file link      -->
    @*<script src="/js/script.js"></script>*@

    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>

    <script>

        AOS.init({
            duration: 800,
        });

    </script>
    <script src="~/js/loginregister.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @*<script src="~/js/site.js" asp-append-version="true"></script>*@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/MvcBurger.Presentation/MvcBurger.Web/Views/Shared/_Order.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MvcBurger</title>

    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css">

    <!-- custom css file link  -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/log.css">

    <style>
        body {
            font-size: 16px;
        }
        h2, p, label, select, option {
            font-size: 1rem;
        }
        h2 {
            font-size: 1.5rem;
        }
    </style>
</head>
<body>
    <!-- header section starts  -->

    <header class="header d-flex align-items-stretch justify-content-between pb-2">

        <div id="menu-btn" class="fas fa-bars icons"></div>
        <div></div>
        <nav class="navbar">
            <div class="row justify-content-sm-between">
                <div class="col-sm-2 mt-3">

                    <a class="text-decoration-none" asp-action="Index" asp-controller="Home">home</a>

                </div>
                <div class="col-sm-2 mt-3">

                    <a class="text-decoration-none" asp-action="Index" asp-controller="Home">menu</a>

                </div>
                <div class="col-sm-4">

                    <img src="/images/logo.png" alt="">

                </div>
                <div class="col-sm-2 mt-3">

                    <a class="text-decoration-none" asp-action="Index" asp-controller="Home">about</a>

                </div>
                <div class="col-sm-2 mt-3">

                    <a class="text-decoration-none" asp-action="Index" asp-controller="Home">contact</a>

                </div>
            </div>
        </nav>
       <div>
            <a asp-action="Cart" asp-controller="Order" class="fas fa-shopping-cart icons m-5"></a>
            @if (!User.Identity.IsAuthenticated)
            {
                <a asp-action="Login" asp-controller="Access" class="fas fa-login icons">Login</a>
                <a asp-action="Register" asp-controller="Access" class="fas fa-register icons">Register</a>
            }
            else
            {
                <a asp-action="Logout" asp-controller="Access" class="fas fa-register icons">Logout</a>
            }
        </div>

    </header>

    <!-- header section ends  -->
    <!-- home section starts  -->

    <section class="home" id="home">
            @RenderBody()
    </section>

    <!-- home section ends -->
    <section class="about" id="about"></section>
    <!-- contact section starts  -->
    <section class="contact" id="contact"></section>
    <!-- contact section ends -->
    <!-- footer section starts  -->

    <section class="footer">

        <div class="links">
            <a asp-action="Index" asp-controller="Home" class="btn">home</a>
            <a asp-action="Index" asp-controller="Home" class="btn">menu</a>
            <a asp-action="Index" asp-controller="Home" class="btn">about</a>
            <a asp-action="Index" asp-controller="Home" class="btn">reviews</a>
            <a asp-action="Index" asp-controller="Home" class="btn">contact</a>
        </div>

        <p class="credit"> created by <span><a href="https://freewebsitecode.com/">Free Website Code</a></span> | all rights reserved! </p><br>

    </section>

    <!-- footer section ends -->
    <!-- custom js file link      -->
    @*<script src="/js/script.js"></script>*@

    @* <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script> *@

    <script>

        AOS.init({
            duration: 800,
        });

    </script>
    <script src="~/js/loginregister.js"></script>
    @* <script src="~/lib/jquery/dist/jquery.min.js"></script> *@
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @*<script src="~/js/site.js" asp-append-version="true"></script>*@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>